---
- name: Create kubeadm Group
  group:
    name: "kube"
    gid: "{{ application_users.kube.gid }}"
    state: present
  become: yes

- name: Create kubeadm User
  user:
    name: "kube"
    comment: "{{ application_users.kube.comment }}"
    group: "kube"
    groups: "{{ application_users.kube.groups }}"
    uid: "{{ application_users.kube.uid }}"
    shell: "/bin/bash"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    ssh_key_comment: "kube@{{ inventory_hostname }}"
    state: present
  become: yes

- name: Collect public keys of kubeadm-users 
  shell: "cat /home/kube/.ssh/id_rsa.pub"
  changed_when: False
  become: yes
  register: ssh_public_key

- name: Set SSH-Key for default Admin User
  authorized_key:
    user: "kube"
    key: "{{ item.key }}"
    state: present
  become: yes
  with_items:
    - "{{ ssh_keys }}"
  when: item["user"] in kubernetes_ssh_keys
      
- name: Set SSH-Key for kubernetes-users
  authorized_key:
    user: "{{ item[1] }}"
    key: "{{ item[2] }}"
    state: present
  delegate_to: "{{ item[0] }}"
  ignore_errors: yes
  become: yes
  with_nested:
    - "{{groups['all_kubernetes']}}"
    - "{{ kubeadm.os_user['user'] }}"
    - "{{ ssh_public_key.stdout }}"
  when: 
    - item[0] in ansible_play_hosts
    - hostvars[item[0]].module_setup is defined